### ISSUE TITLE
Add __toString to EnumInterface

### ISSUE THREAD

**Issue by bigfoot90** [damianopetrungaro/clean-architecture#1]
Add `__toString` to `EnumInterface`, so the enums are printable and comparable.

**Comment by damianopetrungaro** [comment]
@bigfoot90 i implemented the getValue() instead of __toString().

The "getValue" is more explicit instead of using the __toString.
Anyway the [getValue](https://github.com/damianopetrungaro/clean-architecture/blob/master/src/Common/Enum/EnumInterface.php#L34) MUST return a string so it should be perfect 😄

**Comment by bigfoot90** [comment]
`__toString()` can be just a wrapper to `getValue()` but it allows you to print the value just calling the variable/property like on other languages like a shortcat.

Some simple examples:
```
echo $myObject->getType();
echo "SELECT * FROM tbl WHERE type=".$myObject->getType()
```

**Comment by damianopetrungaro** [comment]
I know that it can be a wrapper 😄 .
I simply don't understand why you should print an Enum.

Anyway i am thinking to change the EnumInterface (at the moment it will always  return a string, also when an integer is used as EnumValue).

If you want to can make a PR for add the __toString or during this weekend i'll add it by myself.

**Comment by damianopetrungaro** [comment]
Thank you for the help!
